services:
  web:
    build: 
      context: .
      dockerfile: php/Dockerfile
    ports:
      - "80:80"
    volumes:
      # ホストのlaravel_appディレクトリとコンテナ内のLaravelプロジェクトを同期（開発時用）
      - ./laravel_app:/var/www/html
      - ./composer:/root/.composer  # ←追加（Composer設定永続化用）

    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpass
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
